language: python

python:
  - "2.7"

install:
  - pip install coverage
  - pip install coveralls
  - pip install quantulum

script:
  - coverage run --source=quantulum --omit="*test*" setup.py test
  - coverage report

after_success:
  - coveralls